version: '3'
services:
  fastapi-app:
    image: my-fastapi-app
    container_name: fastapi-app
    working_dir: /app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: always
    depends_on:
      - mongodb
      - redis
    networks:
      - mynetwork
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/IOT_database
      - REDIS_HOST=redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: IOT_database
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/db:/data/db
    restart: always
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
